# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

#EchoNest API Keys
ECHONEST_API_KEY: "SOPAE06QKB7SLUHUZ"
ECHONEST_CONSUMER_KEY: "60d17e7c93300fc37e7f26cfe48317a6"
ECHONEST_SHARED_SECRET: "sDlPOAkwQsaozTJ50IfAzA"

#Dropbox User Info
DROPBOX_USER_ID: "22368238"
DROPBOX_ACCESS_TYPE: "app_folder"

#Misc Vars
INVITE_LIMIT: 3


development:
  # HOST_ADDR: 'http://localhost:3000'
  HOST_ADDR: 'http://soundmelon.ngrok.com'


  ##
  ##Localhost Keys
  #Youtube API Keys
  # YOUTUBE_APP_ID: '1035080270379-o8mnqtq490m1v2v1btgjfl1o54u3v0b3.apps.googleusercontent.com'
  # YOUTUBE_SECRET: '-mEtRYHzGaAqa-035VdwtdiK'
  # YOUTUBE_DEV_KEY: 'AI39si4xwZsnYS8ZPjdY36jy8jGCyBxCavTy1Xj_P5DtaCibNDzilGmeCLRPD9mTz0mHoPhm9LlF2REKzq5ivQQGLRe4g8uqHg'

  # #Soundcloud API Keys
  # SOUNDCLOUD_APP_ID: 'aed36f8bf087fe7716c9e594a211e8fb'
  # SOUNDCLOUD_SECRET: 'dfd9ce380afd86f81619ad1b1dca8d72'

  # #Facebook API Keys
  # FACEBOOK_APP_ID: "220521528108018"
  # FACEBOOK_SECRET: "a2385662ccd25e557324887744e4ff4e"
  
  #Dropbox API Keys
  DROPBOX_APP_KEY: "05fonmrmp17g5am"
  DROPBOX_APP_SECRET: "w2gqpufkalkenw6"
  DROPBOX_ACCESS_TOKEN: "2f1camyaod7fii7d"
  DROPBOX_ACCESS_TOKEN_SECRET: "zdwhiarh0sddo59"
  
  ##
  ##Ngrok Keys
  YOUTUBE_APP_ID: '1035080270379-2hukcfctb6m0mmetrok28h4h7p28hfjg.apps.googleusercontent.com'
  YOUTUBE_SECRET: '7RaYsJE5hvZDqHqlOfFtEbi1'

  #Soundcloud API Keys
  SOUNDCLOUD_APP_ID: 'a0003ecfabe1304a10c8f7e8bfb6d49f'
  SOUNDCLOUD_SECRET: '9b82b1c4c6d531e6d298ba653903028e'

  #Facebook API Keys
  FACEBOOK_APP_ID: "719251288120014"
  FACEBOOK_SECRET: "e828e948b8fdb39ee1e30fba4df3df80"


production:

  #Host Address
  #Staging
#   HOST_ADDR: 'http://soundmelon-stg.herokuapp.com'
  
  #Production
  HOST_ADDR: 'http://www.soundmelon.com'
  
  #Youtube API Keys
  YOUTUBE_APP_ID: '1035080270379-ir19dkk7bs2tsmuritfhpsosugr9nsks.apps.googleusercontent.com'
  YOUTUBE_SECRET: 'OAc7NznbZVV8CDxXN21EZ_OW'

  #Soundcloud API Keys
  #Staging
#   SOUNDCLOUD_APP_ID: 'f935e629060303e3953d1a28a8f39f7d'
#   SOUNDCLOUD_SECRET: '50cd4cb028a187ee49c502d949033df4'
  
  #Production
  SOUNDCLOUD_APP_ID: 'a0abc4d3e9b5e2259a15bf7b4bf5bd7e'
  SOUNDCLOUD_SECRET: '89cd57111d284e6849a871e53161c170'

  #Facebook API Keys
  #Staging
#   FACEBOOK_APP_ID: "181884905339445"
#   FACEBOOK_SECRET: "431da7a7d11969e8d4c811ce7bdae834"
  
  #Production
  FACEBOOK_APP_ID: "229832890501503"
  FACEBOOK_SECRET: "ddc81e09946aec32e6ee543b776c7985"

  #Dropbox API Keys
  #Staging
#   DROPBOX_APP_KEY: "omo0cqzrkq6gjji"
#   DROPBOX_APP_SECRET: "d2lp814khhb80ls"
#   DROPBOX_ACCESS_TOKEN: "ldiw09lev4b5y8sy"
#   DROPBOX_ACCESS_TOKEN_SECRET: "9khtx5y9xklt7aa"
  
  #Production
  DROPBOX_APP_KEY: "pget2g76chyzoby"
  DROPBOX_APP_SECRET: "duw9sg2qicxmk6f"
  DROPBOX_ACCESS_TOKEN: "exyyh7vxk02o3lpz"
  DROPBOX_ACCESS_TOKEN_SECRET: "saw3pnnhpc78hwf" 